import streamlit as st
from openai import OpenAI
import docx
import pdfplumber
import base64
import re
from fpdf import FPDF
import time

# 1. API Configuration
client = OpenAI(
    api_key=st.secrets["DEEPSEEK_API_KEY"], 
    base_url="https://api.deepseek.com"
)

st.set_page_config(page_title="SafeSign AI | Professional Legal Auditor", layout="wide")

# --- Professional Legal Disclaimer ---
def show_disclaimer():
    st.error("""
    **ATTENTION:** This application is an **AI-powered analytical tool** designed for informational purposes only. 
    It **does not constitute legal advice** or an attorney-client relationship. 
    Accuracy is not guaranteed; please consult a **licensed US attorney** before executing any legal instruments.
    """)

# --- Helper Functions ---
def encode_image(image_bytes):
    return base64.b64encode(image_bytes).decode('utf-8')

def redact_sensitive_info(text):
    """PII Protection: Scrus emails and currency amounts"""
    text = re.sub(r'\S+@\S+', '[EMAIL REDACTED]', text)
    text = re.sub(r'\$\d+(?:,\d+)*(?:\.\d+)?', '[AMOUNT REDACTED]', text)
    return text

def create_pdf(text):
    """Generates PDF with character encoding protection"""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', size=16)
    pdf.cell(200, 10, txt="SafeSign AI: Legal Audit Report", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", 'B', size=10)
    pdf.multi_cell(0, 5, txt="IMPORTANT: This report is generated by AI and is NOT a substitute for professional legal counsel.")
    pdf.ln(5)
    pdf.set_font("Arial", size=11)
    # Character Shield logic
    safe_text = text.replace('\u2013', '-').replace('\u2014', '-').replace('\u2018', "'").replace('\u2019', "'").replace('\u201c', '"').replace('\u201d', '"')
    clean_text = safe_text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 8, txt=clean_text)
    return pdf.output(dest="S").encode("latin-1")

# --- Session State ---
if "messages" not in st.session_state:
    st.session_state.messages = []
if "contract_context" not in st.session_state:
    st.session_state.contract_context = ""
if "last_report" not in st.session_state:
    st.session_state.last_report = ""

# 2. Sidebar
with st.sidebar:
    st.title("🛡️ SafeSign AI")
    st.subheader("Global Compliance Suite")
    category = st.selectbox("Audit Protocol", [
        "General Commercial", "SaaS & Tech Services", 
        "Residential Lease", "Employment Agreement", "NDA / Confidentiality"
    ])
    privacy_on = st.toggle("Enable Privacy Scrubbing", value=True)
    if st.button("New Session"):
        st.session_state.clear()
        st.rerun()
    st.divider()
    st.caption("© 2026 SafeSign AI. All rights reserved.")
    st.caption("v5.7 | Pro Enterprise Support")

# 3. Main Dashboard
st.title("AI Contract Audit Dashboard")
show_disclaimer()

uploaded_file = st.file_uploader("Upload Document (PDF, DOCX, or Image Scan)", type=["pdf", "docx", "jpg", "png", "jpeg"])

# --- Enhanced Ingestion with REAL-TIME PROGRESS ---
if uploaded_file and st.session_state.contract_context == "":
    with st.status("Initializing document scan...", expanded=True) as status:
        file_type = uploaded_file.type
        raw_text = ""
        try:
            if "image" in file_type:
                st.write("📷 Performing OCR scan...")
                base64_img = encode_image(uploaded_file.read())
                res = client.chat.completions.create(
                    model="deepseek-chat",
                    messages=[{"role": "user", "content": [{"type": "text", "text": "Extract all text precisely."}, {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_img}"}}]}]
                )
                raw_text = res.choices[0].message.content
            elif "pdf" in file_type:
                with pdfplumber.open(uploaded_file) as pdf:
                    total_pages = len(pdf.pages)
                    # This placeholder creates the "Live Ticker" effect
                    progress_bar = st.empty() 
                    for i, page in enumerate(pdf.pages):
                        # Updating the UI in every loop
                        progress_bar.info(f"📖 Ingesting content: Page {i+1} of {total_pages}...")
                        page_text = page.extract_text()
                        if page_text:
                            raw_text += page_text + "\n"
                    progress_bar.empty() # Clear ticker when done
            elif "wordprocessingml" in file_type:
                st.write("📝 Parsing Word document...")
                doc = docx.Document(uploaded_file)
                raw_text = "\n".join([p.text for p in doc.paragraphs])
            
            if privacy_on:
                st.write("🔒 Scrubbing PII data...")
                raw_text = redact_sensitive_info(raw_text)
            
            st.session_state.contract_context = raw_text
            status.update(label="Document Successfully Loaded!", state="complete", expanded=False)
        except Exception as e:
            st.error(f"Processing Error: {str(e)}")

# 4. Action: Comprehensive Audit
if st.button("🚀 Run AI Risk Audit", type="primary"):
    if st.session_state.contract_context:
        with st.status("Executing Multi-Pass Audit...", expanded=True) as status:
            st.write("🔍 Extracting high-risk clauses...")
            
            system_msg = (
                f"You are a high-level US legal consultant specializing in {category}. "
                "1. Assign a 'Legal Risk Score' (1-100) at the start. "
                "2. Identify Critical Red Flags. 3. Suggest revisions. "
                "IMPORTANT: If a clause is missing, state 'Clause not found'. Be precise."
            )
            
            # Context window protection
            context_payload = st.session_state.contract_context[:28000] 
            
            response = client.chat.completions.create(
                model="deepseek-chat",
                messages=[{"role": "user", "content": f"{system_msg}\n\nContent:\n{context_payload}"}]
            )
            st.write("⚖️ Balancing indemnification and liabilities...")
            st.write("📊 Finalizing executive summary...")
            
            st.session_state.last_report = response.choices[0].message.content
            st.session_state.messages.append({"role": "assistant", "content": st.session_state.last_report})
            status.update(label="Audit Report Ready!", state="complete", expanded=False)
    else:
        st.warning("Please upload a document.")

# 5. Export
if st.session_state.last_report:
    st.divider()
    pdf_data = create_pdf(st.session_state.last_report)
    st.download_button(label="📥 Download Formal Audit Report (PDF)", data=pdf_data, file_name="SafeSign_Audit_Report.pdf", mime="application/pdf")

# 6. Consultation (Refined with Progress)
st.divider()
st.subheader("💬 AI Strategic Consultation")
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

if user_input := st.chat_input("Ex: 'Is the non-compete clause enforceable in California?'"):
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)
    
    with st.chat_message("assistant"):
        with st.status("Reviewing agreement context...", expanded=True) as status:
            st.write("📜 Analyzing document pages...")
            chat_res = client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": f"You are a US legal expert. Context: {st.session_state.contract_context[:8000]}"},
                    *st.session_state.messages
                ]
            )
            st.write("⚖️ Formulating strategic response...")
            ans = chat_res.choices[0].message.content
            status.update(label="Analysis Complete!", state="complete", expanded=False)
        
        st.markdown(ans)
        st.session_state.messages.append({"role": "assistant", "content": ans})